### ISSUE TITLE
1.	School of Performance, Viz, Fine Arts (Priority: high)

### ISSUE THREAD

**Issue by jcreel** [TAMULib/scholars-discovery#187]
Creative work
•	Title*   -  <rdfs:label>
•	Authors   - <http://purl.obolibrary.org/obo/BFO_0000055>
•	Author list (cited authors) *   -<http://vivo.library.tamu.edu/ontology/TAMU#fullAuthorList>
•	Description  - <http://vivoweb.org/ontology/core#description>
•	Artist Role (Controlled voca.; data format: Choice; Requires comments from the school) 
o	Curator
o	Artist
o	Composer
o	Performer
•	Start date*
•	End date
•	Type * (controlled voca.; data format: Choice; Requires comments from the school) - <http://vivo.library.tamu.edu/ontology/TAMU#subtype>
o	Exhibition
o	Performance
o	Painting 
o	Photograph 
o	Sculpture
o	Album
•	Venue (e.g., Chroma Gallery, KOHN Gallery) - <http://vivo.library.tamu.edu/ontology/TAMU#venue
•	Location (e.g., City, State, Country) - <http://vivo.library.tamu.edu/ontology/TAMU#location>
•	URL -   <http://www.w3.org/2006/vcard/ns#url>
•	Note (short description)   -  <http://www.w3.org/2006/vcard/ns#note>

Template:
•	Author name. (Role). (Start date – End date). Title [Type]. Venue, Location, Country. - Note

•	Lee, D.J. (2021, September-2021, December). Title of Art Work [Exhibition]. Art Gallery of College Station, College Station, TX. USA. - Note
•	URL Button
•	Lee, D.J. (Curator). (2021, September-2021, December). Title of Art Work [Exhibition]. Art Gallery of College Station, College Station, TX. - Note
•	Lee, D.J. (2021). Title of Art Work [Painting]. Art Gallery of College Station, College Station, TX. - Note
•	Lee, D.J. (2021). Title of Art Work [Photograph]. Art Gallery of College Station, College Station, TX. - Note
•	Lee, D.J. (2021). Title of Art Work [Sculpture]. Art Gallery of College Station, College Station, TX. - Note
•	Lee, D.J. (2021). Title of Performance Work [Album/Audio]. – Note

**Comment by jcreel** [comment]
[Creative works planning\[2116\].docx](https://github.com/TAMULib/scholars-discovery/files/10024190/Creative.works.planning.2116.docx)

**Comment by ghost** [comment]
- update domain model
- create and test sparql
- update applicable views

**Comment by ghost** [comment]
Remove (Role) from initial default template. Currently all subtypes use the same default template.

**Comment by ghost** [comment]
Switch to use online source badge instead of open access.
