### ISSUE TITLE
2.	Sorting method for educational background (Priority: medium)

### ISSUE THREAD

**Issue by jcreel** [TAMULib/scholars-discovery#188]
a.	Without graduation year, we can’t sort. It is random.
b.	How can we add a way of sorting without year data.

Degrees are sorted by date when provided.  Currently dates are not required resulting in situation a.  We need to require dates and offer optional supression flag for the display.

We would like Doug to add this flag in the editor, and then we would need to respect the value in the display logic.
This is the property the UI will need to respect: http://vivoweb.org/ontology/core#supplementalInformation

In addition, show undated degrees at the bottom.

**Comment by ghost** [comment]
```
// http://localhost:8090/vivo19/display/n3e0f7747
// participates in	n3e0f7747_b0292f15-a806-11e9-bf6d-00155d562649_37a38db5
// date/time interval
// n3e0f7747_b0292f15-a806-11e9-bf6d-00155d562649_37a38db5_interval
// <http://scholars.library.tamu.edu/vivo/individual/n3e0f7747_b0292f15-a806-11e9-bf6d-00155d562649_37a38db5_interval> <http://vivoweb.org/ontology/core#supplementalInformation> "false" .
```

```
                if (strtolower($suppress_year) == strtolower('true')) {
			$suppress_year = "suppress_education_year";
		} else {
			$suppress_year = "display_education_year";
		}
```
