### ISSUE TITLE
3.	Faculty have different titles in different organizations but currently we use their preferred title only for all organization pages. (Priority: medium)

### ISSUE THREAD

**Issue by jcreel** [TAMULib/scholars-discovery#189]
Preference "organization" job title but fall back on HR job title., Filter out all others.
This logic would take the form of a handlebars filter.
Start here: https://github.com/vivo-community/scholars-embed-utilities/blob/main/src/utilities/template.utility.ts#L185

**Comment by ghost** [comment]
Duplicate of https://github.com/TAMULib/scholars-discovery/issues/173
