### ISSUE TITLE
10.	Texas A&M Research in UN SDG, Last 10 Year - Backend API

### ISSUE THREAD

**Issue by jcreel** [TAMULib/scholars-discovery#312]
- University level
- School/College level

Quantity distribution of research, Documents, which have UN SDG goal tag.

1. All documents
2. Documents filtered by organization

**Comment by ghost** [comment]
10.	Texas A&M Research in UN SDG, Last 10 Year [itemId=28095425](https://github.com/orgs/TAMULib/projects/30/views/1?pane=issue&itemId=28095425)
a.	University level
b.	School/College level
