### ISSUE TITLE
Spike: Determine how backend will deliver FILTERS for the visualizations, and how the UI allows filter selection and application

### ISSUE THREAD

**Issue by jcreel** [TAMULib/scholars-discovery#327]

**Comment by ghost** [comment]
I recommended a persistent visualization view that extends existing views that share similar layout. Use Spring Data REST and all code structure in place and abstract among existing views.

**Comment by wwelling** [comment]
Is there a way in which not to persist the API interface instructions to provide to the front-end while still able to extend the front-end UI? For example, the analytic view requires knowing which asynchronous requests it needs to make to provide the necessary visualizations. The existing views required a subset of information already known by the ontology and the decomposition of it. It just so happens to be that the existing views share many of the same requirements as the analytic views.

**Comment by ghost** [comment]
The backend will deliver filter option lookup descriptors which will include query parameters for filters, facets, search, and analytics. 

These require normalization into a persistent entity for runtime configurability, extensibility, and reusability. If not convinced they require persistence, we must consider the UI development and amount of JavaScript that has to be written for both SSR and CSR. While attempting to reuse as much of the same JavaScript for both. The SSR form requests are a bit more involved and require exact matching parameters to the server-side endpoint and must be rendered fully by the server into forms that can be submitted without JavaScript enabled.

Dynamically generating forms on the front end reduces amount of copy and paste performed while creating identical html templates over and over again, these can also be remedied by shared components. It just happens that shared components have too much coupling as the spectrum of features it supports is reused in many routes. Specifications can help reduce shared components extensibility and maintainability however it can always be broken by misuse. Developing code and a specification which cannot be broken even by developers would be some accomplishment.

In advent the server does not provide enough details to render a specific form or form behavior, the domain model persisted requires modification.

As to not convolute other views which already provide persistent for filters, facets, highlights, boosts, etc. They will be a first-class entity that may extend another view to reduce code redundancy but will have ordered list of "lookup templates" in which the SSR/CSR client code will consume and execute during its templating. These templates will include validation that is defined by javax validations in which hibernate respects as well. Spring adds additional layer of validation at application layer and should be used for appropriate RPC and REST responses.

Angular supports reactive forms and can dynamically generated from an asynchronous response. The server-side controller validation response should yield the same feedback to the UI as if the front-end validation CSR JavaScript provides.
