### ISSUE TITLE
On home page: Remove "Tutorials: How To Update"

### ISSUE THREAD

**Issue by C2H5-M** [TAMULib/scholars-discovery#443]
Duplicate of [439](https://github.com/orgs/TAMULib/projects/30/views/16?pane=issue&itemId=89720004&issue=TAMULib%7Cscholars-discovery%7C439).
On Scholars Home page, remove the "Tutorials: How To Update" link, and move the text below it ("Thank you for visiting Scholars@TAMU....") up to replace it in the space provided, increase font size to be the same size as "People" "Organizations" "Research"
![Image](https://github.com/user-attachments/assets/c444534b-1ba6-4ac8-a1b9-317e518ef775)

**Comment by Dbreck-TAMU** [comment]
Update was made in scholars discovery. Please see [Issue 439](https://github.com/orgs/TAMULib/projects/30/views/16?pane=issue&itemId=89720004&issue=TAMULib%7Cscholars-discovery%7C439).
