### ISSUE TITLE
UN Sustainable Development Goal widget on dashboard

### ISSUE THREAD

**Issue by wwelling** [TAMULib/scholars-discovery#92]
A widget would be comprised of all the goals w/icons and be interactive to navigate to a filtered list of persons or publications with designated research tag matching goals.

https://www.un.org/sustainabledevelopment/news/communications-material/

**Image only for reference and not mock-up.**

![image](https://user-images.githubusercontent.com/8352733/120383548-9ef62780-c2ea-11eb-8fa6-d1c6aa301071.png)

**Comment by ghost** [comment]
1. add drop shadow around tooltip
2. use hover event and cache counts
